id: AE47D8449
title: Toh_176-Vimalakirtinirdesa-v1
type: translation
pechas:
- I6136AF2A
- I6CDDDA40
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-07-18T06:29:42.095Z'
  creationid: dirk
  eft-text-id: UT22084-060-005
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_176-Vimalakirtinirdesa-v1
alignment_to_base:
  I6136AF2A/CDE6: F003
  I6CDDDA40/31BF: F003
